// Plantillas estándar de medicación por tipo de cirugía/anestesia.
// Los nombres deben coincidir exactamente con los de DRUGS (drugs.ts).
export interface SurgeryTemplate {
  id: string;
  label: string;
  boluses: string[];
  infusions: string[];
}

export const TEMPLATES: SurgeryTemplate[] = [
  {
    id: "general",
    label: "Anestesia general",
    boluses: [
      "Propofol",
      "Fentanilo",
      "Dexametasona",
      "Rocuronio",
      "Efedrina",
      "Urapidil",
      "Ketamina",
      "Lidocaína",
      "Dexketoprofeno",
      "Metamizol",
      "Paracetamol",
      "Ondansetrón",
      "Droperidol",
      "Sugammadex",
    ],
    infusions: ["Remifentanilo", "Ringer lactato", "Ringer acetato", "Suero fisiológico", "Rocuronio", "Sevoflurano"],
  },
  {
    id: "multimodal",
    label: "Anestesia general multimodal",
    boluses: [
      "Propofol",
      "Dexametasona",
      "Fentanilo",
      "Rocuronio",
      "Efedrina",
      "Urapidil",
      "Fenilefrina",
      "Ketamina",
      "Lidocaína",
      "Sulfato de magnesio",
      "Dexmedetomidina",
      "Dexketoprofeno",
      "Metamizol",
      "Paracetamol",
      "Ondansetrón",
      "Droperidol",
      "Sugammadex",
    ],
    infusions: [
      "Remifentanilo",
      "Ringer lactato",
      "Ringer acetato",
      "Suero fisiológico",
      "Rocuronio",
      "Dexmedetomidina",
      "Ketamina",
      "Sulfato de magnesio",
      "Lidocaína",
      "Sevoflurano",
    ],
  },
  {
    id: "cardiaca",
    label: "Anestesia general · cirugía cardiaca",
    boluses: [
      "Dexametasona",
      "Propofol",
      "Etomidato",
      "Midazolam",
      "Fentanilo",
      "Efedrina",
      "Urapidil",
      "Fenilefrina",
      "Labetalol",
      "Rocuronio",
      "Ketamina",
      "Lidocaína",
      "Dexketoprofeno",
      "Metamizol",
      "Paracetamol",
      "Ondansetrón",
      "Droperidol",
      "Sugammadex",
    ],
    infusions: [
      "Remifentanilo",
      "Ringer lactato",
      "Ringer acetato",
      "Suero fisiológico",
      "Rocuronio",
      "Noradrenalina",
      "Dobutamina",
      "Nitroglicerina",
      "Sevoflurano",
    ],
  },
  {
    id: "intradural",
    label: "Anestesia intradural",
    boluses: [
      "Bupivacaína hiperbara intradural",
      "Bupivacaína intradural",
      "Fentanilo intradural",
      "Morfina intradural",
      "Prilocaína hiperbara intradural",
      "Dexametasona",
      "Dexketoprofeno",
      "Ondansetrón",
      "Paracetamol",
      "Metamizol",
    ],
    infusions: [],
  },
];
